// @ts-nocheck
// NativeToolbox single-file build generated by bundle-single.py
import {
  Button,
  ContentUnavailableView,
  Form,
  HStack,
  Image,
  Label,
  List,
  Navigation,
  NavigationStack,
  Path,
  Picker,
  Script,
  ScrollView,
  Section,
  Spacer,
  Stepper,
  Tab,
  TabView,
  Text,
  TextField,
  Toggle,
  VStack,
  useEffect,
  useObservable,
  useState
} from "scripting"

// ---- models/types.ts ----
type ClipboardKind = "text" | "url" | "image"
type DuplicatePolicy = "ignore" | "moveToTop" | "keepCopy"

type ClipboardItem = {
  id: string
  kind: ClipboardKind
  content: string | null
  asset_path: string | null
  fingerprint: string
  title: string | null
  note: string | null
  is_favorite: number
  is_pinned: number
  created_at: number
  updated_at: number
  last_copied_at: number | null
  expires_at: number | null
  byte_size: number
}

type AppSettings = {
  captureText: boolean
  captureImages: boolean
  duplicatePolicy: DuplicatePolicy
  maxItems: number
  retentionDays: number
}

type SnippetCategory = {
  id: string
  name: string
  symbol: string
  sort_order: number
}

type Snippet = {
  id: string
  category_id: string | null
  title: string
  body: string
  is_template: number
  is_favorite: number
  is_pinned: number
  sort_order: number
  created_at: number
  updated_at: number
}

type LexiconEntry = {
  id: string
  text: string
  code: string | null
  weight: number
  category: string | null
  note: string | null
  source: "manual" | "import" | "workspace"
  workspace_id: string | null
  external_key: string | null
  created_at: number
  updated_at: number
}

type WorkspaceStatus = "connected" | "unavailable" | "changed" | "readonly"

type Workspace = {
  id: string
  type: "wanxiang" | "generic"
  name: string
  bookmark_name: string
  display_path: string
  version: string | null
  last_seen_hash: string | null
  last_checked_at: number | null
  status: WorkspaceStatus
}
// ---- migrations/001-initial.ts ----
type MigrationStep = {
  sql: string
  args?: Array<string | number | boolean | null>
}

type Migration = {
  version: number
  name: string
  steps: MigrationStep[]
}

const initialMigration: Migration = {
  version: 1,
  name: "001-initial",
  steps: [
    { sql: `CREATE TABLE IF NOT EXISTS schema_meta (version INTEGER NOT NULL)` },
    { sql: `CREATE TABLE IF NOT EXISTS clipboard_items (
      id TEXT PRIMARY KEY,
      kind TEXT NOT NULL CHECK(kind IN ('text', 'url', 'image')),
      content TEXT,
      asset_path TEXT,
      fingerprint TEXT NOT NULL,
      title TEXT,
      note TEXT,
      is_favorite INTEGER NOT NULL DEFAULT 0,
      is_pinned INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      last_copied_at INTEGER,
      expires_at INTEGER,
      byte_size INTEGER NOT NULL DEFAULT 0
    )` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_clipboard_fingerprint ON clipboard_items(fingerprint)` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_clipboard_updated ON clipboard_items(updated_at DESC)` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_clipboard_favorite ON clipboard_items(is_favorite, updated_at DESC)` },

    { sql: `CREATE TABLE IF NOT EXISTS tags (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      color TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0
    )` },
    { sql: `CREATE TABLE IF NOT EXISTS clipboard_tags (
      item_id TEXT NOT NULL,
      tag_id TEXT NOT NULL,
      PRIMARY KEY(item_id, tag_id),
      FOREIGN KEY(item_id) REFERENCES clipboard_items(id) ON DELETE CASCADE,
      FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
    )` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_clipboard_tags_tag ON clipboard_tags(tag_id)` },

    { sql: `CREATE TABLE IF NOT EXISTS snippet_categories (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      symbol TEXT NOT NULL,
      sort_order INTEGER NOT NULL DEFAULT 0
    )` },
    { sql: `CREATE UNIQUE INDEX IF NOT EXISTS idx_snippet_categories_name ON snippet_categories(name)` },
    { sql: `CREATE TABLE IF NOT EXISTS snippets (
      id TEXT PRIMARY KEY,
      category_id TEXT,
      title TEXT NOT NULL,
      body TEXT NOT NULL,
      is_template INTEGER NOT NULL DEFAULT 0,
      is_favorite INTEGER NOT NULL DEFAULT 0,
      is_pinned INTEGER NOT NULL DEFAULT 0,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      FOREIGN KEY(category_id) REFERENCES snippet_categories(id) ON DELETE SET NULL
    )` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_snippets_category_order ON snippets(category_id, is_pinned DESC, sort_order)` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_snippets_updated ON snippets(updated_at DESC)` },

    { sql: `CREATE TABLE IF NOT EXISTS text_pipelines (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      steps_json TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL
    )` },
    { sql: `CREATE UNIQUE INDEX IF NOT EXISTS idx_text_pipelines_name ON text_pipelines(name)` },

    { sql: `CREATE TABLE IF NOT EXISTS workspaces (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL CHECK(type IN ('wanxiang', 'generic')),
      name TEXT NOT NULL,
      bookmark_name TEXT NOT NULL,
      display_path TEXT NOT NULL,
      version TEXT,
      last_seen_hash TEXT,
      last_checked_at INTEGER,
      status TEXT NOT NULL CHECK(status IN ('connected', 'unavailable', 'changed', 'readonly'))
    )` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_workspaces_bookmark ON workspaces(bookmark_name)` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_workspaces_status ON workspaces(status)` },

    { sql: `CREATE TABLE IF NOT EXISTS lexicon_entries (
      id TEXT PRIMARY KEY,
      text TEXT NOT NULL,
      code TEXT,
      weight INTEGER NOT NULL DEFAULT 10,
      category TEXT,
      note TEXT,
      source TEXT NOT NULL DEFAULT 'manual',
      workspace_id TEXT,
      external_key TEXT,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL
    )` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_lexicon_text ON lexicon_entries(text)` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_lexicon_code ON lexicon_entries(code)` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_lexicon_workspace ON lexicon_entries(workspace_id, updated_at DESC)` },

    { sql: `CREATE TABLE IF NOT EXISTS workspace_changes (
      id TEXT PRIMARY KEY,
      workspace_id TEXT NOT NULL,
      target_file TEXT NOT NULL,
      operation TEXT NOT NULL CHECK(operation IN ('insert', 'update', 'delete', 'create')),
      payload_json TEXT NOT NULL,
      base_hash TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'applied', 'conflict', 'reverted')),
      FOREIGN KEY(workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
    )` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_workspace_changes_pending ON workspace_changes(workspace_id, status, created_at)` },
    { sql: `CREATE INDEX IF NOT EXISTS idx_workspace_changes_target ON workspace_changes(workspace_id, target_file)` },

    { sql: `INSERT OR IGNORE INTO snippet_categories(id,name,symbol,sort_order) VALUES (?,?,?,?)`, args: ["work", "工作", "briefcase.fill", 0] },
    { sql: `INSERT OR IGNORE INTO snippet_categories(id,name,symbol,sort_order) VALUES (?,?,?,?)`, args: ["life", "生活", "house.fill", 1] },
    { sql: `INSERT OR IGNORE INTO snippet_categories(id,name,symbol,sort_order) VALUES (?,?,?,?)`, args: ["address", "地址", "mappin.and.ellipse", 2] },
    { sql: `INSERT OR IGNORE INTO snippet_categories(id,name,symbol,sort_order) VALUES (?,?,?,?)`, args: ["code", "代码", "chevron.left.forwardslash.chevron.right", 3] },

    { sql: `UPDATE schema_meta SET version = 1` },
    { sql: `INSERT INTO schema_meta(version) SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM schema_meta)` },
  ],
}
// ---- migrations/index.ts ----
type AppliedMigration = {
  version: number
  name: string
  checksum: string
  applied_at: number
}

type MigrationReport = {
  fromVersion: number
  toVersion: number
  applied: string[]
  backupDirectory: string | null
}

const migrations: Migration[] = [initialMigration]

async function tableExists(db: Database, tableName: string) {
  const rows = await db.fetchAll<{ name: string }>(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ? LIMIT 1",
    [tableName],
  )
  return rows.length > 0
}

async function columnNames(db: Database, tableName: string) {
  const rows = await db.fetchAll<{ name: string }>(`PRAGMA table_info("${tableName}")`)
  return rows.map(row => row.name)
}

function checksumFor(migration: Migration) {
  const data = Data.fromRawString(JSON.stringify({
    version: migration.version,
    name: migration.name,
    steps: migration.steps,
  }))
  if (data == null) throw new Error(`无法计算数据库迁移 ${migration.version} 的校验值`)
  return Crypto.sha256(data).toHexString()
}

async function ensureMigrationTable(db: Database) {
  await db.execute(`CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_at INTEGER NOT NULL
  )`)
}

async function readAppliedMigrations(db: Database) {
  const rows = await db.fetchAll<AppliedMigration>(
    "SELECT version,name,checksum,applied_at FROM schema_migrations ORDER BY version"
  )
  return new Map(rows.map(row => [row.version, row]))
}

function timestampName() {
  const d = new Date()
  const pad = (value: number) => String(value).padStart(2, "0")
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`
}

async function checkpointIfPossible(db: Database) {
  // Scripting keeps extra SQLite reader connections. FULL waits for them to
  // finish and can throw SQLITE_LOCKED (error 6) during startup.
  try {
    await db.execute("PRAGMA wal_checkpoint(PASSIVE)")
  } catch (error) {
    console.warn("WAL checkpoint skipped", error)
  }
}

function backupDatabaseFiles(databasePath: string, backupsDirectory: string) {
  if (!FileManager.existsSync(databasePath)) return null
  const directory = Path.join(backupsDirectory, `migration-${timestampName()}`)
  FileManager.createDirectorySync(directory, true)
  for (const suffix of ["", "-wal", "-shm"]) {
    const source = `${databasePath}${suffix}`
    if (FileManager.existsSync(source)) {
      FileManager.copyFileSync(source, Path.join(directory, `toolbox.sqlite${suffix}`))
    }
  }
  const marker = Data.fromRawString(JSON.stringify({
    createdAt: Date.now(),
    reason: "before-schema-migration",
  }, null, 2))
  if (marker != null) {
    FileManager.writeAsDataSync(Path.join(directory, "backup.json"), marker)
  }
  return directory
}

async function backupIfPossible(db: Database, databasePath: string, backupsDirectory: string) {
  await checkpointIfPossible(db)
  try {
    return backupDatabaseFiles(databasePath, backupsDirectory)
  } catch (error) {
    console.warn("Database backup skipped", error)
    return null
  }
}

async function runMigrations(
  db: Database,
  databasePath: string,
  backupsDirectory: string,
): Promise<MigrationReport> {
  const hadMigrationTable = await tableExists(db, "schema_migrations")
  const legacyMetaExists = await tableExists(db, "schema_meta")
  let legacyVersion = 0
  if (legacyMetaExists) {
    const rows = await db.fetchAll<{ version: number }>("SELECT version FROM schema_meta LIMIT 1")
    legacyVersion = rows[0]?.version ?? 0
  }

  const backupDirectory = !hadMigrationTable && legacyMetaExists
    ? await backupIfPossible(db, databasePath, backupsDirectory)
    : null

  await ensureMigrationTable(db)
  const applied = await readAppliedMigrations(db)
  const appliedNames: string[] = []

  for (const migration of migrations) {
    const checksum = checksumFor(migration)
    const existing = applied.get(migration.version)
    if (existing != null) {
      if (existing.name !== migration.name || existing.checksum !== checksum) {
        throw new Error(`数据库迁移 ${migration.version} 校验失败，请从备份恢复或升级脚本`)
      }
      continue
    }

    await db.transaction([
      ...migration.steps,
      {
        sql: "INSERT INTO schema_migrations(version,name,checksum,applied_at) VALUES (?,?,?,?)",
        args: [migration.version, migration.name, checksum, Date.now()],
      },
    ], { kind: "immediate" })
    appliedNames.push(migration.name)
  }

  const latest = migrations[migrations.length - 1]?.version ?? 0
  return {
    fromVersion: legacyVersion,
    toVersion: latest,
    applied: appliedNames,
    backupDirectory,
  }
}

const requiredTables = [
  "schema_migrations",
  "clipboard_items",
  "tags",
  "clipboard_tags",
  "snippet_categories",
  "snippets",
  "text_pipelines",
  "workspaces",
  "lexicon_entries",
  "workspace_changes",
]

const requiredColumns: Record<string, string[]> = {
  clipboard_items: ["id", "kind", "content", "fingerprint", "is_favorite", "updated_at"],
  snippets: ["id", "category_id", "title", "body", "updated_at"],
  workspaces: ["id", "type", "bookmark_name", "status"],
  lexicon_entries: ["id", "text", "code", "weight", "workspace_id"],
  workspace_changes: ["id", "workspace_id", "target_file", "base_hash", "status"],
}

async function validateSchema(db: Database) {
  const errors: string[] = []
  for (const table of requiredTables) {
    if (!(await tableExists(db, table))) errors.push(`缺少数据表：${table}`)
  }
  for (const [table, expected] of Object.entries(requiredColumns)) {
    if (!(await tableExists(db, table))) continue
    const names = new Set(await columnNames(db, table))
    for (const name of expected) {
      if (!names.has(name)) errors.push(`数据表 ${table} 缺少字段 ${name}`)
    }
  }
  if (errors.length > 0) throw new Error(errors.join("；"))
  return true
}
// ---- services/database.ts ----
const rootDirectory = Path.join(FileManager.documentsDirectory, "NativeToolbox")
const databasePath = Path.join(rootDirectory, "toolbox.sqlite")
const assetsDirectory = Path.join(rootDirectory, "assets", "clipboard")
const exportsDirectory = Path.join(rootDirectory, "exports")
const backupsDirectory = Path.join(rootDirectory, "backups")
const logsDirectory = Path.join(rootDirectory, "logs")

// SQLite.open 要求父目录已经存在；同步创建发生在模块初始化阶段。
if (!FileManager.existsSync(rootDirectory)) {
  FileManager.createDirectorySync(rootDirectory, true)
}

const paths = {
  rootDirectory,
  databasePath,
  assetsDirectory,
  exportsDirectory,
  backupsDirectory,
  logsDirectory,
}

async function ensureAppDirectories() {
  for (const path of [rootDirectory, assetsDirectory, exportsDirectory, backupsDirectory, logsDirectory]) {
    if (!(await FileManager.exists(path))) {
      await FileManager.createDirectory(path, true)
    }
  }
}

const db = SQLite.open(databasePath, {
  foreignKeysEnabled: true,
  journalMode: "wal",
  busyMode: 5,
  maximumReaderCount: 3,
  label: "native-toolbox-main",
})

async function migrateDatabase() {
  await ensureAppDirectories()
  const report = await runMigrations(db, databasePath, backupsDirectory)
  await validateSchema(db)
  return report
}

async function listClipboardItems(query = "", kind: "all" | "text" | "url" | "image" | "favorite" = "all") {
  const filters: string[] = []
  const args: Array<string | number> = []
  if (query.trim()) {
    filters.push("(content LIKE ? OR title LIKE ? OR note LIKE ?)")
    const q = `%${query.trim()}%`
    args.push(q, q, q)
  }
  if (kind === "favorite") filters.push("is_favorite = 1")
  else if (kind !== "all") {
    filters.push("kind = ?")
    args.push(kind)
  }
  const where = filters.length ? `WHERE ${filters.join(" AND ")}` : ""
  return db.fetchAll<ClipboardItem>(`
    SELECT * FROM clipboard_items
    ${where}
    ORDER BY is_pinned DESC, updated_at DESC
    LIMIT 1000
  `, args)
}

async function findClipboardByFingerprint(fingerprint: string) {
  return db.fetchAll<ClipboardItem>(
    "SELECT * FROM clipboard_items WHERE fingerprint = ? ORDER BY updated_at DESC LIMIT 1",
    [fingerprint]
  ).then(rows => rows[0] ?? null)
}

async function insertClipboardItem(item: ClipboardItem) {
  await db.execute(`
    INSERT INTO clipboard_items(
      id,kind,content,asset_path,fingerprint,title,note,is_favorite,is_pinned,
      created_at,updated_at,last_copied_at,expires_at,byte_size
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `, [
    item.id, item.kind, item.content, item.asset_path, item.fingerprint,
    item.title, item.note, item.is_favorite, item.is_pinned, item.created_at,
    item.updated_at, item.last_copied_at, item.expires_at, item.byte_size,
  ])
}

async function touchClipboardItem(id: string, now: number) {
  await db.execute("UPDATE clipboard_items SET updated_at = ? WHERE id = ?", [now, id])
}

async function toggleClipboardFavorite(id: string) {
  await db.execute(`
    UPDATE clipboard_items
    SET is_favorite = CASE WHEN is_favorite = 1 THEN 0 ELSE 1 END,
        updated_at = ?
    WHERE id = ?
  `, [Date.now(), id])
}

async function deleteClipboardItem(id: string) {
  await db.execute("DELETE FROM clipboard_items WHERE id = ?", [id])
}

async function markClipboardCopied(id: string) {
  await db.execute("UPDATE clipboard_items SET last_copied_at = ? WHERE id = ?", [Date.now(), id])
}

async function cleanupClipboard(maxItems: number, now: number) {
  await db.execute("DELETE FROM clipboard_items WHERE is_favorite = 0 AND expires_at IS NOT NULL AND expires_at < ?", [now])
  await db.execute(`
    DELETE FROM clipboard_items
    WHERE is_favorite = 0 AND id IN (
      SELECT id FROM clipboard_items
      WHERE is_favorite = 0
      ORDER BY updated_at DESC
      LIMIT -1 OFFSET ?
    )
  `, [maxItems])
}

async function listWorkspaces() {
  return db.fetchAll<Workspace>("SELECT * FROM workspaces ORDER BY name")
}

async function findWorkspaceByBookmark(bookmarkName: string) {
  const rows = await db.fetchAll<Workspace>(
    "SELECT * FROM workspaces WHERE bookmark_name = ? ORDER BY last_checked_at DESC LIMIT 1",
    [bookmarkName],
  )
  return rows[0] ?? null
}

async function upsertWorkspace(workspace: Workspace) {
  await db.execute(`
    INSERT INTO workspaces(
      id,type,name,bookmark_name,display_path,version,last_seen_hash,last_checked_at,status
    ) VALUES (?,?,?,?,?,?,?,?,?)
    ON CONFLICT(id) DO UPDATE SET
      type=excluded.type,
      name=excluded.name,
      bookmark_name=excluded.bookmark_name,
      display_path=excluded.display_path,
      version=excluded.version,
      last_seen_hash=excluded.last_seen_hash,
      last_checked_at=excluded.last_checked_at,
      status=excluded.status
  `, [
    workspace.id, workspace.type, workspace.name, workspace.bookmark_name,
    workspace.display_path, workspace.version, workspace.last_seen_hash,
    workspace.last_checked_at, workspace.status,
  ])
}

async function removeWorkspace(id: string) {
  await db.execute("DELETE FROM workspaces WHERE id = ?", [id])
}

async function listSnippetCategories() {
  return db.fetchAll<SnippetCategory>(
    "SELECT * FROM snippet_categories ORDER BY sort_order, name"
  )
}

async function listSnippets(
  query = "",
  options: { favoriteOnly?: boolean; categoryId?: string | null } = {},
) {
  const filters: string[] = []
  const args: Array<string | number> = []
  if (query.trim()) {
    filters.push("(title LIKE ? OR body LIKE ?)")
    const q = `%${query.trim()}%`
    args.push(q, q)
  }
  if (options.favoriteOnly) filters.push("is_favorite = 1")
  if (options.categoryId) {
    filters.push("category_id = ?")
    args.push(options.categoryId)
  }
  const where = filters.length ? `WHERE ${filters.join(" AND ")}` : ""
  return db.fetchAll<Snippet>(`
    SELECT * FROM snippets
    ${where}
    ORDER BY is_pinned DESC, is_favorite DESC, sort_order, updated_at DESC
    LIMIT 1000
  `, args)
}

async function upsertSnippet(snippet: Snippet) {
  await db.execute(`
    INSERT INTO snippets(
      id,category_id,title,body,is_template,is_favorite,is_pinned,sort_order,created_at,updated_at
    ) VALUES (?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(id) DO UPDATE SET
      category_id=excluded.category_id,
      title=excluded.title,
      body=excluded.body,
      is_template=excluded.is_template,
      is_favorite=excluded.is_favorite,
      is_pinned=excluded.is_pinned,
      sort_order=excluded.sort_order,
      updated_at=excluded.updated_at
  `, [
    snippet.id, snippet.category_id, snippet.title, snippet.body,
    snippet.is_template, snippet.is_favorite, snippet.is_pinned,
    snippet.sort_order, snippet.created_at, snippet.updated_at,
  ])
}

async function toggleSnippetFavorite(id: string) {
  await db.execute(`
    UPDATE snippets
    SET is_favorite = CASE WHEN is_favorite = 1 THEN 0 ELSE 1 END,
        updated_at = ?
    WHERE id = ?
  `, [Date.now(), id])
}

async function deleteSnippet(id: string) {
  await db.execute("DELETE FROM snippets WHERE id = ?", [id])
}

async function countLexiconEntries() {
  const rows = await db.fetchAll<{ total: number }>("SELECT COUNT(*) AS total FROM lexicon_entries")
  return rows[0]?.total ?? 0
}

async function listLexiconEntries(query = "") {
  const filters: string[] = []
  const args: Array<string | number> = []
  if (query.trim()) {
    filters.push("(text LIKE ? OR IFNULL(code, '') LIKE ? OR IFNULL(category, '') LIKE ? OR IFNULL(note, '') LIKE ?)")
    const q = `%${query.trim()}%`
    args.push(q, q, q, q)
  }
  const where = filters.length ? `WHERE ${filters.join(" AND ")}` : ""
  return db.fetchAll<LexiconEntry>(`
    SELECT * FROM lexicon_entries
    ${where}
    ORDER BY updated_at DESC
    LIMIT 1000
  `, args)
}

async function upsertLexiconEntry(entry: LexiconEntry) {
  await db.execute(`
    INSERT INTO lexicon_entries(
      id,text,code,weight,category,note,source,workspace_id,external_key,created_at,updated_at
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(id) DO UPDATE SET
      text=excluded.text,
      code=excluded.code,
      weight=excluded.weight,
      category=excluded.category,
      note=excluded.note,
      source=excluded.source,
      workspace_id=excluded.workspace_id,
      external_key=excluded.external_key,
      updated_at=excluded.updated_at
  `, [
    entry.id, entry.text, entry.code, entry.weight, entry.category, entry.note,
    entry.source, entry.workspace_id, entry.external_key, entry.created_at, entry.updated_at,
  ])
}

async function deleteLexiconEntry(id: string) {
  await db.execute("DELETE FROM lexicon_entries WHERE id = ?", [id])
}

async function findLexiconEntryByTextCode(text: string, code: string) {
  const rows = await db.fetchAll<LexiconEntry>(
    "SELECT * FROM lexicon_entries WHERE text = ? AND IFNULL(code, '') = ? LIMIT 1",
    [text, code],
  )
  return rows[0] ?? null
}

type ExternalPhraseImport = {
  text: string
  code: string
  weight: number | null
  workspaceId: string
}

type PhraseImportResult = {
  imported: number
  skipped: number
}

async function importExternalPhrases(items: ExternalPhraseImport[]): Promise<PhraseImportResult> {
  let imported = 0
  let skipped = 0
  for (const item of items) {
    const code = item.code.trim()
    const text = item.text.trim()
    if (!text || !code) {
      skipped += 1
      continue
    }
    const existing = await findLexiconEntryByTextCode(text, code)
    if (existing != null) {
      skipped += 1
      continue
    }
    const now = Date.now()
    await upsertLexiconEntry({
      id: UUID.string(),
      text,
      code,
      weight: item.weight ?? 10,
      category: null,
      note: null,
      source: "workspace",
      workspace_id: item.workspaceId,
      external_key: `${text}\u0000${code}`,
      created_at: now,
      updated_at: now,
    })
    imported += 1
  }
  return { imported, skipped }
}
// ---- services/pasteboard.ts ----
const DEFAULT_SETTINGS: AppSettings = {
  captureText: true,
  captureImages: false,
  duplicatePolicy: "moveToTop",
  maxItems: 500,
  retentionDays: 30,
}

const SETTINGS_KEY = "native-toolbox.settings.v1"
const CHANGE_COUNT_KEY = "native-toolbox.pasteboard.changeCount"

function loadSettings(): AppSettings {
  return {
    ...DEFAULT_SETTINGS,
    ...(Storage.get<Partial<AppSettings>>(SETTINGS_KEY) ?? {}),
  }
}

function saveSettings(settings: AppSettings) {
  return Storage.set(SETTINGS_KEY, settings)
}

function normalizeText(text: string) {
  return text.replace(/\r\n?/g, "\n").replace(/[ \t]+$/gm, "").trimEnd()
}

function asData(value: string) {
  const data = Data.fromRawString(value)
  if (data == null) throw new Error("无法将文本编码为 UTF-8")
  return data
}

function fingerprint(kind: ClipboardKind, content: string) {
  return Crypto.sha256(asData(`${kind}\u0000${content}`)).toHexString()
}

function looksLikeURL(text: string) {
  return /^https?:\/\/\S+$/i.test(text.trim())
}

async function captureTextValue(raw: string, settings: AppSettings) {
  const content = normalizeText(raw)
  if (!content) return false
  const kind: ClipboardKind = looksLikeURL(content) ? "url" : "text"
  const hash = fingerprint(kind, content)
  const existing = await findClipboardByFingerprint(hash)
  const now = Date.now()

  if (existing && settings.duplicatePolicy === "ignore") return false
  if (existing && settings.duplicatePolicy === "moveToTop") {
    await touchClipboardItem(existing.id, now)
    return true
  }

  const item: ClipboardItem = {
    id: UUID.string(),
    kind,
    content,
    asset_path: null,
    fingerprint: hash,
    title: null,
    note: null,
    is_favorite: 0,
    is_pinned: 0,
    created_at: now,
    updated_at: now,
    last_copied_at: null,
    expires_at: settings.retentionDays > 0
      ? now + settings.retentionDays * 24 * 60 * 60 * 1000
      : null,
    byte_size: asData(content).size,
  }
  await insertClipboardItem(item)
  await cleanupClipboard(settings.maxItems, now)
  return true
}

async function captureCurrentPasteboard(settings = loadSettings()) {
  let changed = false
  if (settings.captureText) {
    const values = await Pasteboard.getStrings()
    for (const value of values ?? []) {
      changed = (await captureTextValue(value, settings)) || changed
    }
  }

  // 图片写盘在第二个开发切片实现；开关保留但不会把图片误存进 Storage。
  const count = await Pasteboard.changeCount
  Storage.set(CHANGE_COUNT_KEY, count)
  return changed
}

async function captureIfChanged(settings = loadSettings()) {
  const current = await Pasteboard.changeCount
  const previous = Storage.get<number>(CHANGE_COUNT_KEY)
  if (previous === current) return false
  return captureCurrentPasteboard(settings)
}

function installPasteboardListener(onCaptured: () => void) {
  Pasteboard.onChanged = () => {
    captureCurrentPasteboard()
      .then((changed: boolean) => changed && onCaptured())
      .catch((error: unknown) => console.error("Pasteboard capture failed", error))
  }
  return () => {
    Pasteboard.onChanged = null
  }
}
// ---- features/clipboard/ClipboardScreen.tsx ----
type Filter = "all" | "text" | "url" | "favorite"

function relativeTime(timestamp: number) {
  const delta = Math.max(0, Date.now() - timestamp)
  const minute = 60_000
  const hour = 60 * minute
  const day = 24 * hour
  if (delta < minute) return "刚刚"
  if (delta < hour) return `${Math.floor(delta / minute)} 分钟前`
  if (delta < day) return `${Math.floor(delta / hour)} 小时前`
  return `${Math.floor(delta / day)} 天前`
}

function ClipboardRow({ item, reload }: { item: ClipboardItem; reload: () => void }) {
  const icon = item.kind === "url" ? "link" : "doc.text"
  const copy = async () => {
    if (item.content != null) {
      await Pasteboard.setString(item.content)
      await markClipboardCopied(item.id)
      reload()
    }
  }

  return (
    <HStack spacing={12}
      onTapGesture={copy}
      leadingSwipeActions={{
        allowsFullSwipe: false,
        actions: [
          <Button
            title={item.is_favorite ? "取消收藏" : "收藏"}
            systemImage={item.is_favorite ? "star.slash" : "star"}
            tint="systemOrange"
            action={async () => {
              await toggleClipboardFavorite(item.id)
              reload()
            }}
          />,
        ],
      }}
      trailingSwipeActions={{
        actions: [
          <Button
            title="删除"
            systemImage="trash"
            role="destructive"
            action={async () => {
              await deleteClipboardItem(item.id)
              reload()
            }}
          />,
        ],
      }}
    >
      <Image systemName={icon} foregroundColor="secondary" />
      <VStack alignment="leading" spacing={4} frame={{ maxWidth: "infinity", alignment: "leading" }}>
        <Text font="body" lineLimit={3}>{item.content ?? ""}</Text>
        <Text font="caption" foregroundColor="secondary">
          {item.kind === "url" ? "链接" : "文本"} · {relativeTime(item.updated_at)}
          {item.is_favorite === 1 ? " · 已收藏" : ""}
        </Text>
      </VStack>
    </HStack>
  )
}

function ClipboardScreen() {
  const [items, setItems] = useState<ClipboardItem[]>([])
  const [query, setQuery] = useState("")
  const [filter, setFilter] = useState<Filter>("all")
  const [loading, setLoading] = useState(true)
  const [capturing, setCapturing] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const reload = () => {
    listClipboardItems(query, filter)
      .then(setItems)
      .catch(e => setError(String(e)))
      .finally(() => setLoading(false))
  }

  useEffect(() => {
    reload()
  }, [query, filter])

  useEffect(() => {
    const remove = installPasteboardListener(reload)
    return remove
  }, [])

  const capture = async () => {
    if (capturing) return
    setCapturing(true)
    setError(null)
    try {
      const changed = await captureCurrentPasteboard(loadSettings())
      reload()
      if (!changed) {
        await Dialog.alert({
          title: "没有新内容",
          message: "系统剪贴板是空的，或这条已经在列表里。先复制一段文字再点采集。",
        })
      }
    } catch (e) {
      await Dialog.alert({ title: "采集失败", message: String(e) })
      setError(String(e))
    } finally {
      setCapturing(false)
    }
  }

  const overlay = error != null
    ? <ContentUnavailableView title="无法读取剪贴板" systemImage="exclamationmark.triangle" description={error} />
    : (!loading && items.length === 0
      ? <ContentUnavailableView
          label={<Text>暂无剪贴板内容</Text>}
          description={<Text>复制一段文字，或点击“立即采集”。</Text>}
          actions={[<Button title="立即采集" systemImage="arrow.clockwise" action={capture} />]}
        />
      : undefined)

  return (
    <NavigationStack>
      <List
        navigationTitle="剪贴板"
        navigationBarTitleDisplayMode="large"
        listStyle="insetGrouped"
        searchable={{ value: query, onChanged: setQuery, prompt: "搜索" }}
        overlay={overlay}
        toolbar={{
          primaryAction: (
            <Button
              title={capturing ? "采集中" : "采集"}
              systemImage="arrow.clockwise"
              disabled={capturing}
              action={capture}
            />
          ),
        }}
      >
        <Section
          header={<Text>筛选</Text>}
          footer={items.length > 0 ? <Text>点按复制，左滑收藏，右滑删除。</Text> : undefined}
        >
          <Picker
            title="类型"
            pickerStyle="segmented"
            value={filter}
            onChanged={value => setFilter(value as Filter)}
          >
            <Text tag="all">全部</Text>
            <Text tag="text">文本</Text>
            <Text tag="url">链接</Text>
            <Text tag="favorite">收藏</Text>
          </Picker>
        </Section>
        {items.length > 0 && <Section>
          {items.map(item => <ClipboardRow key={item.id} item={item} reload={reload} />)}
        </Section>}
      </List>
    </NavigationStack>
  )
}
// ---- features/snippets/templates.ts ----
const KNOWN_TEMPLATE_KEYS = ["date", "time", "datetime", "clipboard"] as const

type TemplateKey = (typeof KNOWN_TEMPLATE_KEYS)[number]

type TemplateContext = {
  now?: Date
  clipboard?: string | null
}

type TemplateRenderResult = {
  text: string
  missing: string[]
}

const TOKEN = /\{\{\s*([^{}]+?)\s*\}\}/g

function pad(value: number) {
  return String(value).padStart(2, "0")
}

function formatDate(now: Date) {
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`
}

function formatTime(now: Date) {
  return `${pad(now.getHours())}:${pad(now.getMinutes())}`
}

function formatDateTime(now: Date) {
  return `${formatDate(now)} ${formatTime(now)}`
}

function extractTemplateKeys(body: string) {
  const keys = new Set<string>()
  for (const match of body.matchAll(TOKEN)) {
    const key = match[1].trim()
    if (key) keys.add(key)
  }
  return [...keys]
}

function looksLikeTemplate(body: string) {
  return extractTemplateKeys(body).length > 0
}

function renderSnippetTemplate(body: string, context: TemplateContext = {}): TemplateRenderResult {
  const now = context.now ?? new Date()
  const missing: string[] = []
  const values: Record<string, string | undefined> = {
    date: formatDate(now),
    time: formatTime(now),
    datetime: formatDateTime(now),
    clipboard: context.clipboard?.trim() ? context.clipboard.trim() : undefined,
  }

  const text = body.replace(TOKEN, (_all, rawKey: string) => {
    const key = rawKey.trim()
    const value = values[key]
    if (value != null && value !== "") return value
    if (!missing.includes(key)) missing.push(key)
    return `{{${key}}}`
  })

  return { text, missing }
}

async function currentClipboardText() {
  const values = await Pasteboard.getStrings()
  const first = (values ?? []).find(value => value.trim().length > 0)
  return first ?? ""
}
// ---- features/snippets/SnippetsScreen.tsx ----
type Scope = "all" | "favorite"

function relativeTime(timestamp: number) {
  const delta = Math.max(0, Date.now() - timestamp)
  const minute = 60_000
  const hour = 60 * minute
  const day = 24 * hour
  if (delta < minute) return "刚刚"
  if (delta < hour) return `${Math.floor(delta / minute)} 分钟前`
  if (delta < day) return `${Math.floor(delta / hour)} 小时前`
  return `${Math.floor(delta / day)} 天前`
}

function previewBody(body: string) {
  return body.replace(/\s+/g, " ").trim()
}

function emptySnippet(categoryId: string | null): Snippet {
  const now = Date.now()
  return {
    id: UUID.string(),
    category_id: categoryId,
    title: "",
    body: "",
    is_template: 0,
    is_favorite: 0,
    is_pinned: 0,
    sort_order: 0,
    created_at: now,
    updated_at: now,
  }
}

function SnippetEditor({
  snippet,
  categories,
  onClose,
}: {
  snippet: Snippet
  categories: SnippetCategory[]
  onClose: (saved: boolean) => void
}) {
  const [title, setTitle] = useState(snippet.title)
  const [body, setBody] = useState(snippet.body)
  const [categoryId, setCategoryId] = useState(snippet.category_id ?? "none")
  const [favorite, setFavorite] = useState(snippet.is_favorite === 1)
  const [saving, setSaving] = useState(false)

  const save = async () => {
    const nextTitle = title.trim()
    const nextBody = body.replace(/\s+$/g, "")
    if (!nextTitle) {
      await Dialog.alert({ title: "请填写标题", message: "常用语需要一个简短标题，方便搜索和复制。" })
      return
    }
    if (!nextBody.trim()) {
      await Dialog.alert({ title: "请填写内容", message: "正文不能为空。" })
      return
    }
    setSaving(true)
    try {
      await upsertSnippet({
        ...snippet,
        title: nextTitle,
        body: nextBody,
        category_id: categoryId === "none" ? null : categoryId,
        is_favorite: favorite ? 1 : 0,
        is_template: looksLikeTemplate(nextBody) ? 1 : 0,
        updated_at: Date.now(),
      })
      onClose(true)
    } catch (error) {
      await Dialog.alert({ title: "保存失败", message: String(error) })
      setSaving(false)
    }
  }

  return (
    <NavigationStack>
      <List
        navigationTitle={snippet.title ? "编辑常用语" : "新建常用语"}
        navigationBarTitleDisplayMode="inline"
        listStyle="insetGrouped"
        toolbar={{
          cancellationAction: <Button title="取消" action={() => onClose(false)} />,
          confirmationAction: <Button title={saving ? "保存中…" : "保存"} disabled={saving} action={save} />,
        }}
      >
        <Section>
          <TextField title="标题" value={title} onChanged={setTitle} prompt="例如：公司地址" />
          <Picker
            title="分类"
            value={categoryId}
            onChanged={setCategoryId}
          >
            <Text tag="none">未分类</Text>
            {categories.map(category => (
              <Text key={category.id} tag={category.id}>{category.name}</Text>
            ))}
          </Picker>
          <Toggle title="收藏" value={favorite} onChanged={setFavorite} />
        </Section>
        <Section
          header={<Text>内容</Text>}
          footer={<Text>可用变量：{"{{date}}"}、{"{{time}}"}、{"{{datetime}}"}、{"{{clipboard}}"}。未填写的变量会提示，不会被偷偷删掉。</Text>}
        >
          <TextField
            title="正文"
            value={body}
            onChanged={setBody}
            axis="vertical"
            lineLimit={{ max: 10 }}
            prompt="输入常用语正文"
          />
        </Section>
      </List>
    </NavigationStack>
  )
}

function SnippetRow({
  snippet,
  categoryName,
  onEdit,
  reload,
}: {
  snippet: Snippet
  categoryName: string
  onEdit: () => void
  reload: () => void
}) {
  const copy = async () => {
    const clipboard = extractTemplateKeys(snippet.body).includes("clipboard")
      ? await currentClipboardText()
      : ""
    const rendered = renderSnippetTemplate(snippet.body, { clipboard })
    if (rendered.missing.length > 0) {
      await Dialog.alert({
        title: "变量未填写",
        message: `还缺少：${rendered.missing.map(key => `{{${key}}}`).join("、")}。请补全后再复制。`,
      })
      return
    }
    await Pasteboard.setString(rendered.text)
  }

  return (
    <HStack spacing={12}
      onTapGesture={copy}
      leadingSwipeActions={{
        allowsFullSwipe: false,
        actions: [
          <Button
            title="编辑"
            systemImage="pencil"
            tint="systemBlue"
            action={onEdit}
          />,
          <Button
            title={snippet.is_favorite ? "取消收藏" : "收藏"}
            systemImage={snippet.is_favorite ? "star.slash" : "star"}
            tint="systemOrange"
            action={async () => {
              await toggleSnippetFavorite(snippet.id)
              reload()
            }}
          />,
        ],
      }}
      trailingSwipeActions={{
        actions: [
          <Button
            title="删除"
            systemImage="trash"
            role="destructive"
            action={async () => {
              const confirmed = await Dialog.confirm({
                title: "删除常用语",
                message: `确定删除「${snippet.title}」？`,
                confirmLabel: "删除",
                cancelLabel: "取消",
              })
              if (!confirmed) return
              await deleteSnippet(snippet.id)
              reload()
            }}
          />,
        ],
      }}
    >
      <VStack alignment="leading" spacing={4} frame={{ maxWidth: "infinity", alignment: "leading" }}>
        <Text font="body" lineLimit={1}>{snippet.title}</Text>
        <Text font="subheadline" foregroundColor="secondary" lineLimit={2}>{previewBody(snippet.body)}</Text>
        <Text font="caption" foregroundColor="secondary">
          {categoryName}
          {snippet.is_favorite === 1 ? " · 已收藏" : ""}
        </Text>
      </VStack>
    </HStack>
  )
}

function SnippetsScreen() {
  const [items, setItems] = useState<Snippet[]>([])
  const [categories, setCategories] = useState<SnippetCategory[]>([])
  const [query, setQuery] = useState("")
  const [scope, setScope] = useState<Scope>("all")
  const [categoryFilter, setCategoryFilter] = useState("all")
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [editor, setEditor] = useState<Snippet | null>(null)

  const reload = () => {
    Promise.all([
      listSnippets(query, {
        favoriteOnly: scope === "favorite",
        categoryId: categoryFilter === "all" ? null : categoryFilter,
      }),
      listSnippetCategories(),
    ])
      .then(([nextItems, nextCategories]) => {
        setItems(nextItems)
        setCategories(nextCategories)
        setError(null)
      })
      .catch(e => setError(String(e)))
      .finally(() => setLoading(false))
  }

  useEffect(() => {
    reload()
  }, [query, scope, categoryFilter])

  const categoryName = (id: string | null) => {
    if (id == null) return "未分类"
    return categories.find(category => category.id === id)?.name ?? "未分类"
  }

  const createFromClipboard = async () => {
    const text = (await currentClipboardText()).trim()
    if (!text) {
      await Dialog.alert({ title: "剪贴板是空的", message: "先复制一段文字，再从剪贴板创建常用语。" })
      return
    }
    const title = previewBody(text).slice(0, 24) || "未命名常用语"
    setEditor({
      ...emptySnippet(categoryFilter === "all" ? null : categoryFilter),
      title,
      body: text,
      is_template: looksLikeTemplate(text) ? 1 : 0,
    })
  }

  const overlay = error != null
    ? <ContentUnavailableView title="无法读取常用语" systemImage="exclamationmark.triangle" description={error} />
    : (!loading && items.length === 0
      ? <ContentUnavailableView
          label={<Text>{query ? "没有匹配的常用语" : "还没有常用语"}</Text>}
          description={<Text>可手动新建，或把剪贴板里的文字保存成常用语。</Text>}
          actions={[
            <Button title="新建常用语" systemImage="plus" action={() => setEditor(emptySnippet(null))} />,
            <Button title="从剪贴板创建" systemImage="doc.on.clipboard" action={createFromClipboard} />,
          ]}
        />
      : undefined)

  return (
    <NavigationStack>
      <List
        navigationTitle="常用语"
        navigationBarTitleDisplayMode="large"
        listStyle="insetGrouped"
        searchable={{ value: query, onChanged: setQuery, prompt: "搜索" }}
        overlay={overlay}
        toolbar={{
          primaryAction: <Button title="新建" systemImage="plus" action={() => setEditor(emptySnippet(categoryFilter === "all" ? null : categoryFilter))} />,
          topBarTrailing: <Button title="从剪贴板" systemImage="doc.on.clipboard" action={createFromClipboard} />,
        }}
        sheet={{
          isPresented: editor != null,
          onChanged: presented => { if (!presented) setEditor(null) },
          content: editor == null ? undefined : (
            <SnippetEditor
              key={editor.id}
              snippet={editor}
              categories={categories}
              onClose={saved => {
                setEditor(null)
                if (saved) reload()
              }}
            />
          ),
        }}
      >
        <Section footer={items.length > 0 ? <Text>点按复制，左滑编辑或收藏，右滑删除。</Text> : undefined}>
          <Picker
            title="范围"
            pickerStyle="segmented"
            value={scope}
            onChanged={value => setScope(value as Scope)}
          >
            <Text tag="all">全部</Text>
            <Text tag="favorite">收藏</Text>
          </Picker>
          {categories.length > 0 && (
            <Picker
              title="分类"
              value={categoryFilter}
              onChanged={setCategoryFilter}
            >
              <Text tag="all">全部</Text>
              {categories.map(category => (
                <Text key={category.id} tag={category.id}>{category.name}</Text>
              ))}
            </Picker>
          )}
        </Section>
        {items.length > 0 && <Section>
          {items.map(item => (
            <SnippetRow
              key={item.id}
              snippet={item}
              categoryName={categoryName(item.category_id)}
              onEdit={() => setEditor(item)}
              reload={reload}
            />
          ))}
        </Section>}
      </List>
    </NavigationStack>
  )
}
// ---- features/textlab/processors.ts ----
function trimWhitespace(input: string) {
  return input.replace(/\r\n?/g, "\n").trim()
}

function mergeBlankLines(input: string) {
  return input.replace(/\r\n?/g, "\n").replace(/\n{3,}/g, "\n\n")
}

function removeEmptyLines(input: string) {
  return input.replace(/\r\n?/g, "\n").split("\n").filter(line => line.trim().length > 0).join("\n")
}

function dedupeLines(input: string) {
  const seen = new Set<string>()
  return input.replace(/\r\n?/g, "\n").split("\n").filter(line => {
    if (seen.has(line)) return false
    seen.add(line)
    return true
  }).join("\n")
}

function sortLines(input: string) {
  return input.replace(/\r\n?/g, "\n").split("\n").sort((a, b) => a.localeCompare(b, "zh-Hans-CN")).join("\n")
}

function formatJSON(input: string) {
  return JSON.stringify(JSON.parse(input), null, 2)
}

type TextOperation = "trim" | "blankLines" | "removeEmpty" | "dedupe" | "sort" | "json"

function applyTextOperation(input: string, operation: TextOperation) {
  switch (operation) {
    case "trim": return trimWhitespace(input)
    case "blankLines": return mergeBlankLines(input)
    case "removeEmpty": return removeEmptyLines(input)
    case "dedupe": return dedupeLines(input)
    case "sort": return sortLines(input)
    case "json": return formatJSON(input)
  }
}
// ---- features/textlab/TextLabScreen.tsx ----
function TextLabScreen() {
  const [mode, setMode] = useState<"input" | "result">("input")
  const [source, setSource] = useState("")
  const [result, setResult] = useState("")
  const [error, setError] = useState<string | null>(null)

  const run = async (operation: TextOperation) => {
    try {
      const output = applyTextOperation(source, operation)
      setResult(output)
      setMode("result")
      setError(null)
    } catch (e) {
      setError(String(e))
    }
  }

  const paste = async () => {
    const values = await Pasteboard.getStrings()
    const text = (values ?? []).find(value => value.trim().length > 0) ?? ""
    if (!text) {
      await Dialog.alert({ title: "剪贴板是空的", message: "先复制一段文字，再点粘贴。" })
      return
    }
    setSource(text)
    setMode("input")
    setError(null)
  }

  const copyResult = async () => {
    if (!result) {
      await Dialog.alert({ title: "还没有结果", message: "先处理一段文字。" })
      return
    }
    await Pasteboard.setString(result)
  }

  return (
    <NavigationStack>
      <List
        navigationTitle="文本"
        navigationBarTitleDisplayMode="large"
        listStyle="insetGrouped"
        toolbar={{
          primaryAction: <Button title="粘贴" systemImage="doc.on.clipboard" action={paste} />,
          topBarTrailing: <Button title="复制结果" systemImage="doc.on.doc" action={copyResult} />,
        }}
      >
        <Section>
          <Picker
            title="显示"
            pickerStyle="segmented"
            value={mode}
            onChanged={value => setMode(value as "input" | "result")}
          >
            <Text tag="input">输入</Text>
            <Text tag="result">结果</Text>
          </Picker>
        </Section>
        <Section
          header={<Text>{mode === "input" ? "原文" : "结果"}</Text>}
          footer={<Text>在输入框里粘贴或编辑，再用下面的工具处理。</Text>}
        >
          {mode === "input" ? (
            <TextField
              title="原文"
              value={source}
              onChanged={setSource}
              axis="vertical"
              lineLimit={{ min: 8, max: 16 }}
              prompt="在这里输入或粘贴文字"
            />
          ) : (
            <TextField
              title="结果"
              value={result}
              onChanged={() => {}}
              axis="vertical"
              lineLimit={{ min: 8, max: 16 }}
              prompt="处理结果会显示在这里"
            />
          )}
        </Section>
        {error != null && (
          <Section>
            <Text foregroundColor="systemRed">{error}</Text>
          </Section>
        )}
        <Section header={<Text>工具</Text>}>
          <ScrollView axis="horizontal" showsIndicators={false}>
            <HStack spacing={8}>
              <Button title="清理空白" buttonStyle="bordered" action={() => run("trim")} />
              <Button title="合并空行" buttonStyle="bordered" action={() => run("blankLines")} />
              <Button title="删除空行" buttonStyle="bordered" action={() => run("removeEmpty")} />
              <Button title="行去重" buttonStyle="bordered" action={() => run("dedupe")} />
              <Button title="行排序" buttonStyle="bordered" action={() => run("sort")} />
              <Button title="JSON" buttonStyle="bordered" action={() => run("json")} />
            </HStack>
          </ScrollView>
        </Section>
      </List>
    </NavigationStack>
  )
}
// ---- adapters/wanxiang/custom-phrase.ts ----
type PhraseKind = "comment" | "blank" | "entry" | "invalid"

type PhraseLine = {
  lineNumber: number
  raw: string
  kind: PhraseKind
  text?: string
  code?: string
  weight?: number | null
  error?: string
}

type PhraseEntry = {
  key: string
  text: string
  code: string
  weight: number | null
  lineNumber: number
}

type PhraseDocument = {
  lines: PhraseLine[]
  entries: PhraseEntry[]
  invalid: PhraseLine[]
  hash: string
}

type PhraseChangeKind = "insert" | "update" | "same" | "externalOnly"

type PhraseDiffItem = {
  kind: PhraseChangeKind
  key: string
  text: string
  code: string
  internalWeight: number | null
  externalWeight: number | null
  internalNote?: string | null
}

type PhraseDiff = {
  inserts: PhraseDiffItem[]
  updates: PhraseDiffItem[]
  same: PhraseDiffItem[]
  externalOnly: PhraseDiffItem[]
  invalid: PhraseLine[]
  hash: string
  path: string
}

function phraseKey(text: string, code: string) {
  return `${text}\u0000${code}`
}

function parseWeight(value: string | undefined) {
  if (value == null || value.trim() === "") return null
  const number = Number(value.trim())
  if (!Number.isInteger(number)) return null
  return number
}

function parseCustomPhrase(content: string): Omit<PhraseDocument, "hash"> {
  const lines: PhraseLine[] = []
  const entries: PhraseEntry[] = []
  const invalid: PhraseLine[] = []

  content.replace(/\r\n?/g, "\n").split("\n").forEach((raw, index) => {
    const lineNumber = index + 1
    const trimmed = raw.trim()
    if (trimmed === "") {
      lines.push({ lineNumber, raw, kind: "blank" })
      return
    }
    if (trimmed.startsWith("#")) {
      lines.push({ lineNumber, raw, kind: "comment" })
      return
    }

    if (raw.includes(" ") && !raw.includes("\t")) {
      const invalidLine: PhraseLine = {
        lineNumber,
        raw,
        kind: "invalid",
        error: "数据行必须使用 Tab 分隔，不能用空格假冒",
      }
      lines.push(invalidLine)
      invalid.push(invalidLine)
      return
    }

    const parts = raw.split("\t")
    const text = (parts[0] ?? "").trim()
    const code = (parts[1] ?? "").trim()
    const weightRaw = parts[2]
    if (!text || !code || parts.length > 3) {
      const invalidLine: PhraseLine = {
        lineNumber,
        raw,
        kind: "invalid",
        error: !text || !code ? "缺少词语或编码" : "列数过多",
      }
      lines.push(invalidLine)
      invalid.push(invalidLine)
      return
    }

    const weight = parseWeight(weightRaw)
    if (weightRaw != null && weightRaw.trim() !== "" && weight == null) {
      const invalidLine: PhraseLine = {
        lineNumber,
        raw,
        kind: "invalid",
        text,
        code,
        error: "权重必须是整数",
      }
      lines.push(invalidLine)
      invalid.push(invalidLine)
      return
    }

    const entry: PhraseEntry = {
      key: phraseKey(text, code),
      text,
      code,
      weight,
      lineNumber,
    }
    lines.push({ lineNumber, raw, kind: "entry", text, code, weight })
    entries.push(entry)
  })

  return { lines, entries, invalid }
}

function hashCustomPhrase(content: string) {
  const data = Data.fromRawString(content)
  if (data == null) throw new Error("custom_phrase.txt 不是有效 UTF-8 文本")
  return Crypto.sha256(data).toHexString()
}

function parseCustomPhraseDocument(content: string): PhraseDocument {
  return {
    ...parseCustomPhrase(content),
    hash: hashCustomPhrase(content),
  }
}

type InternalPhrase = {
  text: string
  code: string | null
  weight: number
  note?: string | null
}

function diffCustomPhrase(internal: InternalPhrase[], document: PhraseDocument, path: string): PhraseDiff {
  const external = new Map(document.entries.map(entry => [entry.key, entry]))
  const inserts: PhraseDiffItem[] = []
  const updates: PhraseDiffItem[] = []
  const same: PhraseDiffItem[] = []
  const seen = new Set<string>()

  for (const item of internal) {
    const code = item.code?.trim() ?? ""
    if (!code) continue
    const key = phraseKey(item.text, code)
    if (seen.has(key)) continue
    seen.add(key)
    const existing = external.get(key)
    const diffItem: PhraseDiffItem = {
      kind: "same",
      key,
      text: item.text,
      code,
      internalWeight: item.weight,
      externalWeight: existing?.weight ?? null,
      internalNote: item.note ?? null,
    }
    if (existing == null) {
      inserts.push({ ...diffItem, kind: "insert" })
    } else if ((existing.weight ?? null) !== item.weight) {
      updates.push({ ...diffItem, kind: "update" })
    } else {
      same.push(diffItem)
    }
  }

  const externalOnly: PhraseDiffItem[] = []
  for (const entry of document.entries) {
    if (seen.has(entry.key)) continue
    externalOnly.push({
      kind: "externalOnly",
      key: entry.key,
      text: entry.text,
      code: entry.code,
      internalWeight: null,
      externalWeight: entry.weight,
    })
  }

  return {
    inserts,
    updates,
    same,
    externalOnly,
    invalid: document.invalid,
    hash: document.hash,
    path,
  }
}

const MANAGED_BEGIN = "# >>> NativeToolbox managed entries"
const MANAGED_END = "# <<< NativeToolbox managed entries"

function formatEntry(text: string, code: string, weight: number | null) {
  return weight == null ? `${text}\t${code}` : `${text}\t${code}\t${weight}`
}

function applyCustomPhraseDiff(original: string, diff: PhraseDiff) {
  if (diff.invalid.length > 0) {
    throw new Error("外部 custom_phrase.txt 有格式异常行，禁止提交")
  }
  const updates = new Map(diff.updates.map(item => [item.key, item]))
  const kept: string[] = []
  let inManaged = false

  for (const raw of original.replace(/\r\n?/g, "\n").split("\n")) {
    const trimmed = raw.trim()
    if (trimmed === MANAGED_BEGIN) {
      inManaged = true
      continue
    }
    if (trimmed === MANAGED_END) {
      inManaged = false
      continue
    }
    if (inManaged) continue
    if (trimmed === "" || trimmed.startsWith("#") || !raw.includes("\t")) {
      kept.push(raw)
      continue
    }
    const parts = raw.split("\t")
    const text = (parts[0] ?? "").trim()
    const code = (parts[1] ?? "").trim()
    const update = updates.get(phraseKey(text, code))
    if (update) {
      kept.push(formatEntry(update.text, update.code, update.internalWeight))
    } else {
      kept.push(raw)
    }
  }

  while (kept.length > 0 && kept[kept.length - 1].trim() === "") kept.pop()

  const managed = [
    MANAGED_BEGIN,
    ...diff.inserts.map(item => formatEntry(item.text, item.code, item.internalWeight)),
    MANAGED_END,
  ]
  const body = kept.join("\n").replace(/\n+$/g, "")
  if (diff.inserts.length === 0) return `${body}\n`
  return `${body}\n\n${managed.join("\n")}\n`
}
// ---- services/workspace-bookmarks.ts ----
function hashText(text: string) {
  const data = Data.fromRawString(text)
  if (data == null) throw new Error("文件不是有效 UTF-8 文本")
  return Crypto.sha256(data).toHexString()
}

function basename(path: string) {
  return path.split("/").filter(Boolean).pop() ?? "工作区"
}

async function chooseAndConnectWorkspace() {
  const result = await DocumentPicker.pickDirectoryBookmark({
    preferredName: "NativeToolbox Wanxiang",
  })
  if (result == null) return null

  const root = FileManager.bookmarkedPath(result.bookmarkName)
  if (root == null) throw new Error("目录授权已保存，但无法恢复访问路径")

  const schemaPath = Path.join(root, "wanxiang.schema.yaml")
  const versionPath = Path.join(root, "version.txt")
  const isWanxiang = await FileManager.exists(schemaPath)
  const version = await FileManager.exists(versionPath)
    ? (await FileManager.readAsString(versionPath)).trim()
    : null
  const schemaText = isWanxiang ? await FileManager.readAsString(schemaPath) : ""

  const existing = await findWorkspaceByBookmark(result.bookmarkName)
  const workspace: Workspace = {
    id: existing?.id ?? UUID.string(),
    type: isWanxiang ? "wanxiang" : "generic",
    name: isWanxiang ? "万象拼音" : basename(root),
    bookmark_name: result.bookmarkName,
    display_path: root,
    version,
    last_seen_hash: isWanxiang ? hashText(schemaText) : null,
    last_checked_at: Date.now(),
    status: "connected",
  }
  await upsertWorkspace(workspace)
  return workspace
}

async function refreshWorkspace(workspace: Workspace) {
  const root = FileManager.bookmarkedPath(workspace.bookmark_name)
  if (root == null) {
    return { ...workspace, status: "unavailable" as const, last_checked_at: Date.now() }
  }
  const schemaPath = Path.join(root, "wanxiang.schema.yaml")
  if (workspace.type === "wanxiang" && !(await FileManager.exists(schemaPath))) {
    return { ...workspace, status: "unavailable" as const, last_checked_at: Date.now() }
  }
  const versionPath = Path.join(root, "version.txt")
  const version = await FileManager.exists(versionPath)
    ? (await FileManager.readAsString(versionPath)).trim()
    : null
  return { ...workspace, display_path: root, version, status: "connected" as const, last_checked_at: Date.now() }
}
// ---- services/wanxiang-preview.ts ----
function timestampName() {
  const d = new Date()
  const pad = (value: number) => String(value).padStart(2, "0")
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`
}

async function resolvePhrasePath(workspace: Workspace) {
  const root = FileManager.bookmarkedPath(workspace.bookmark_name) ?? workspace.display_path
  if (!root) throw new Error("工作区目录无法访问")
  const path = Path.join(root, "custom_phrase.txt")
  if (!(await FileManager.exists(path))) {
    throw new Error("这个目录里没有 custom_phrase.txt")
  }
  return { root, path }
}

async function readCustomPhraseFile(workspace: Workspace) {
  const { path } = await resolvePhrasePath(workspace)
  const content = await FileManager.readAsString(path)
  return { path, content, document: parseCustomPhraseDocument(content) }
}

async function previewCustomPhraseDiff(workspace: Workspace, internal: InternalPhrase[]): Promise<PhraseDiff> {
  if (workspace.type !== "wanxiang") {
    throw new Error("只有已识别的万象目录才能预览 custom_phrase.txt")
  }
  if (workspace.status !== "connected") {
    throw new Error("工作区未连接，请先重新授权目录")
  }
  const { path, document } = await readCustomPhraseFile(workspace)
  return diffCustomPhrase(internal, document, path)
}

type PhraseCommitResult = {
  backupPath: string
  inserted: number
  updated: number
  hash: string
}

async function commitCustomPhraseDiff(
  workspace: Workspace,
  internal: InternalPhrase[],
  expectedHash: string,
): Promise<PhraseCommitResult> {
  if (workspace.type !== "wanxiang") {
    throw new Error("只有已识别的万象目录才能提交 custom_phrase.txt")
  }
  if (workspace.status !== "connected") {
    throw new Error("工作区未连接，请先重新授权目录")
  }

  const { root, path } = await resolvePhrasePath(workspace)
  const current = await FileManager.readAsString(path)
  const currentHash = hashCustomPhrase(current)
  if (currentHash !== expectedHash) {
    throw new Error("custom_phrase.txt 在预览后已被外部修改，已禁止覆盖。请重新预览后再提交。")
  }

  const document = parseCustomPhraseDocument(current)
  const diff = diffCustomPhrase(internal, document, path)
  if (diff.invalid.length > 0) {
    throw new Error("外部文件仍有格式异常行，禁止提交")
  }
  if (diff.inserts.length + diff.updates.length === 0) {
    throw new Error("没有可提交的差异")
  }

  const nextContent = applyCustomPhraseDiff(current, diff)
  const parsedNext = parseCustomPhraseDocument(nextContent)
  if (parsedNext.invalid.length > 0) {
    throw new Error("合成后的 custom_phrase.txt 无法通过解析，已中止写入")
  }
  for (const item of [...diff.inserts, ...diff.updates]) {
    const found = parsedNext.entries.find(entry => entry.key === item.key)
    if (found == null || found.weight !== item.internalWeight) {
      throw new Error(`合成结果缺少或未更新「${item.text} / ${item.code}」`)
    }
  }

  const backupRoot = Path.join(root, "ToolboxBackups", timestampName())
  await FileManager.createDirectory(backupRoot, true)
  const backupPath = Path.join(backupRoot, "custom_phrase.txt")
  FileManager.copyFileSync(path, backupPath)

  const tempPath = Path.join(root, `custom_phrase.txt.toolbox-${timestampName()}.tmp`)
  await FileManager.writeAsString(tempPath, nextContent)
  const tempText = await FileManager.readAsString(tempPath)
  const tempParsed = parseCustomPhraseDocument(tempText)
  if (tempParsed.invalid.length > 0 || tempParsed.hash !== parsedNext.hash) {
    if (await FileManager.exists(tempPath)) FileManager.removeSync(tempPath)
    throw new Error("临时文件校验失败，已删除临时文件，原文件未改动")
  }

  const replacePath = Path.join(root, `custom_phrase.txt.replacing-${timestampName()}`)
  FileManager.copyFileSync(tempPath, replacePath)
  if (await FileManager.exists(path)) FileManager.removeSync(path)
  FileManager.copyFileSync(replacePath, path)
  FileManager.removeSync(tempPath)
  FileManager.removeSync(replacePath)

  const written = await FileManager.readAsString(path)
  const writtenHash = hashCustomPhrase(written)
  if (writtenHash !== parsedNext.hash) {
    FileManager.copyFileSync(backupPath, path)
    throw new Error("写入后哈希不一致，已从备份恢复原文件")
  }

  return {
    backupPath,
    inserted: diff.inserts.length,
    updated: diff.updates.length,
    hash: writtenHash,
  }
}
// ---- features/lexicon/PhraseDiffSheet.tsx ----
function DiffRow({ item, detail }: { item: PhraseDiffItem; detail: string }) {
  return (
    <VStack alignment="leading" spacing={4}>
      <Text font="headline">{item.text}</Text>
      <Text font="subheadline" foregroundColor="secondary">{item.code} · {detail}</Text>
    </VStack>
  )
}

function PhraseDiffSheet({
  diff,
  onClose,
  onCommit,
  onImportExternal,
}: {
  diff: PhraseDiff
  onClose: () => void
  onCommit?: () => Promise<void>
  onImportExternal?: () => Promise<void>
}) {
  const pending = diff.inserts.length + diff.updates.length
  const [committing, setCommitting] = useState(false)
  const [importing, setImporting] = useState(false)
  const canCommit = pending > 0 && diff.invalid.length === 0 && onCommit != null
  const canImport = diff.externalOnly.length > 0 && onImportExternal != null && !committing

  const commit = async () => {
    if (!canCommit || committing) return
    const confirmed = await Dialog.confirm({
      title: "提交到万象？",
      message: `将新增 ${diff.inserts.length} 条、更新 ${diff.updates.length} 条权重。提交前会备份原文件；不会删除仅外部存在的词条，也不会改 userdb / gram / 官方 dicts。`,
      confirmLabel: "提交",
      cancelLabel: "取消",
    })
    if (!confirmed) return
    setCommitting(true)
    try {
      await onCommit()
    } catch (error) {
      await Dialog.alert({ title: "提交失败", message: String(error) })
    } finally {
      setCommitting(false)
    }
  }

  const importExternal = async () => {
    if (!canImport || importing) return
    const confirmed = await Dialog.confirm({
      title: "导入到内部词库？",
      message: `将导入 ${diff.externalOnly.length} 条仅外部存在的词条。相同词语+编码不会覆盖；这次不会改 custom_phrase.txt。`,
      confirmLabel: "导入",
      cancelLabel: "取消",
    })
    if (!confirmed) return
    setImporting(true)
    try {
      await onImportExternal()
    } catch (error) {
      await Dialog.alert({ title: "导入失败", message: String(error) })
    } finally {
      setImporting(false)
    }
  }

  return (
    <NavigationStack>
      <List
        navigationTitle="差异预览"
        navigationBarTitleDisplayMode="inline"
        listStyle="insetGrouped"
        toolbar={{
          topBarLeading: <Button title="完成" action={onClose} />,
          confirmationAction: canCommit
            ? <Button title={committing ? "提交中…" : "提交"} disabled={committing} action={commit} />
            : undefined,
        }}
      >
        <Section footer={<Text>
          {canCommit
            ? "确认后才会写入 custom_phrase.txt。提交前会备份，并再次核对文件哈希。"
            : "当前没有可提交差异，或外部文件有异常行。"}
        </Text>}>
          <HStack>
            <Text>待新增</Text>
            <Spacer />
            <Text foregroundColor="secondary">{diff.inserts.length}</Text>
          </HStack>
          <HStack>
            <Text>待更新权重</Text>
            <Spacer />
            <Text foregroundColor="secondary">{diff.updates.length}</Text>
          </HStack>
          <HStack>
            <Text>已一致</Text>
            <Spacer />
            <Text foregroundColor="secondary">{diff.same.length}</Text>
          </HStack>
          <HStack>
            <Text>仅外部存在</Text>
            <Spacer />
            <Text foregroundColor="secondary">{diff.externalOnly.length}</Text>
          </HStack>
          <HStack>
            <Text>格式异常</Text>
            <Spacer />
            <Text foregroundColor="secondary">{diff.invalid.length}</Text>
          </HStack>
        </Section>
        {diff.inserts.length > 0 && (
          <Section header={<Text>将新增到万象</Text>}>
            {diff.inserts.map(item => (
              <DiffRow
                key={`insert-${item.key}`}
                item={item}
                detail={`内部权重 ${item.internalWeight ?? "-"}`}
              />
            ))}
          </Section>
        )}
        {diff.updates.length > 0 && (
          <Section header={<Text>权重不同</Text>}>
            {diff.updates.map(item => (
              <DiffRow
                key={`update-${item.key}`}
                item={item}
                detail={`内部 ${item.internalWeight ?? "-"} → 外部 ${item.externalWeight ?? "-"}`}
              />
            ))}
          </Section>
        )}
        {diff.invalid.length > 0 && (
          <Section header={<Text>外部文件异常行</Text>} footer={<Text>这些行不会被提交覆盖；请先在万象文件里修好。</Text>}>
            {diff.invalid.map(line => (
              <VStack key={`invalid-${line.lineNumber}`} alignment="leading" spacing={4}>
                <Text font="headline">第 {line.lineNumber} 行</Text>
                <Text font="caption" foregroundColor="secondary">{line.error ?? "无法解析"}</Text>
                <Text font="caption2" foregroundColor="secondary" lineLimit={3}>{line.raw}</Text>
              </VStack>
            ))}
          </Section>
        )}
        {diff.externalOnly.length > 0 && (
          <Section
            header={<Text>仅外部存在</Text>}
            footer={<Text>这些词条只在万象文件里。导入后进入内部词库，不会覆盖已有相同词语+编码，也不会改外部文件。</Text>}
          >
            {canImport && (
              <Button
                title={importing ? "导入中…" : `导入这 ${diff.externalOnly.length} 条`}
                systemImage="square.and.arrow.down"
                disabled={importing}
                action={importExternal}
              />
            )}
            {diff.externalOnly.slice(0, 30).map(item => (
              <DiffRow
                key={`external-${item.key}`}
                item={item}
                detail={`外部权重 ${item.externalWeight ?? "默认"}`}
              />
            ))}
            {diff.externalOnly.length > 30 && (
              <Text foregroundColor="secondary">还有 {diff.externalOnly.length - 30} 条未展开</Text>
            )}
          </Section>
        )}
        {pending === 0 && diff.invalid.length === 0 && (
          <Section>
            <Text>内部有编码的词条已经和 custom_phrase.txt 一致，没有可提交差异。</Text>
          </Section>
        )}
      </List>
    </NavigationStack>
  )
}
// ---- features/lexicon/LexiconScreen.tsx ----
function emptyEntry(): LexiconEntry {
  const now = Date.now()
  return {
    id: UUID.string(),
    text: "",
    code: "",
    weight: 10,
    category: "",
    note: "",
    source: "manual",
    workspace_id: null,
    external_key: null,
    created_at: now,
    updated_at: now,
  }
}

function preview(value: string | null) {
  return (value ?? "").replace(/\s+/g, " ").trim()
}

function WorkspaceRow({
  workspace,
  reload,
  onPreview,
}: {
  workspace: Workspace
  reload: () => void
  onPreview: () => void
}) {
  const connected = workspace.status === "connected"
  return (
    <HStack spacing={12}
      onTapGesture={connected && workspace.type === "wanxiang" ? onPreview : undefined}
      trailingSwipeActions={{
        actions: [
          <Button
            title="断开"
            systemImage="link.badge.minus"
            role="destructive"
            action={async () => {
              await removeWorkspace(workspace.id)
              reload()
            }}
          />,
        ],
      }}
    >
      <Image systemName="square.stack.3d.up.fill" foregroundColor="systemIndigo" />
      <VStack alignment="leading" spacing={4}>
        <Text font="headline">{workspace.name}</Text>
        <Text font="caption" foregroundColor="secondary">
          {workspace.type === "wanxiang" ? `Base · v${workspace.version ?? "未知"}` : "通用目录"}
        </Text>
        <Text font="caption2" foregroundColor="secondary" lineLimit={1}>{workspace.display_path}</Text>
      </VStack>
      <Spacer />
      <Text font="caption" foregroundColor="secondary">
        {connected ? (workspace.type === "wanxiang" ? "预览差异" : "已连接") : "需重新授权"}
      </Text>
    </HStack>
  )
}

function LexiconEditor({
  entry,
  onClose,
}: {
  entry: LexiconEntry
  onClose: (saved: boolean) => void
}) {
  const [text, setText] = useState(entry.text)
  const [code, setCode] = useState(entry.code ?? "")
  const [weight, setWeight] = useState(entry.weight)
  const [category, setCategory] = useState(entry.category ?? "")
  const [note, setNote] = useState(entry.note ?? "")
  const [saving, setSaving] = useState(false)

  const save = async () => {
    const nextText = text.trim()
    if (!nextText) {
      await Dialog.alert({ title: "请填写词语", message: "内部词条至少需要词语本身。" })
      return
    }
    setSaving(true)
    try {
      await upsertLexiconEntry({
        ...entry,
        text: nextText,
        code: code.trim() || null,
        weight,
        category: category.trim() || null,
        note: note.trim() || null,
        source: "manual",
        updated_at: Date.now(),
      })
      onClose(true)
    } catch (error) {
      await Dialog.alert({ title: "保存失败", message: String(error) })
      setSaving(false)
    }
  }

  return (
    <NavigationStack>
      <List
        navigationTitle={entry.text ? "编辑词条" : "新建词条"}
        navigationBarTitleDisplayMode="inline"
        listStyle="insetGrouped"
        toolbar={{
          cancellationAction: <Button title="取消" action={() => onClose(false)} />,
          confirmationAction: <Button title={saving ? "保存中…" : "保存"} disabled={saving} action={save} />,
        }}
      >
        <Section footer={<Text>这些词条先存在工具箱自己的数据库里，不会写入万象目录。</Text>}>
          <TextField title="词语" value={text} onChanged={setText} prompt="例如：毛豆" />
          <TextField title="编码" value={code} onChanged={setCode} prompt="可选，例如 maodou" />
          <Stepper
            title={`权重 ${weight}`}
            onIncrement={() => setWeight(Math.min(100, weight + 1))}
            onDecrement={() => setWeight(Math.max(1, weight - 1))}
          />
          <TextField title="分类" value={category} onChanged={setCategory} prompt="可选" />
        </Section>
        <Section header={<Text>备注</Text>}>
          <TextField
            title="备注"
            value={note}
            onChanged={setNote}
            axis="vertical"
            lineLimit={{ max: 6 }}
            prompt="可选说明"
          />
        </Section>
      </List>
    </NavigationStack>
  )
}

function LexiconRow({
  entry,
  onEdit,
  reload,
}: {
  entry: LexiconEntry
  onEdit: () => void
  reload: () => void
}) {
  const copy = async () => {
    await Pasteboard.setString(entry.text)
  }

  const subtitle = [entry.code, entry.category, `权重 ${entry.weight}`]
    .filter(value => value != null && String(value).trim() !== "")
    .join(" · ")

  return (
    <HStack spacing={12}
      onTapGesture={copy}
      leadingSwipeActions={{
        allowsFullSwipe: false,
        actions: [
          <Button title="编辑" systemImage="pencil" tint="systemBlue" action={onEdit} />,
        ],
      }}
      trailingSwipeActions={{
        actions: [
          <Button
            title="删除"
            systemImage="trash"
            role="destructive"
            action={async () => {
              const confirmed = await Dialog.confirm({
                title: "删除词条",
                message: `确定删除「${entry.text}」？`,
                confirmLabel: "删除",
                cancelLabel: "取消",
              })
              if (!confirmed) return
              await deleteLexiconEntry(entry.id)
              reload()
            }}
          />,
        ],
      }}
    >
      <VStack alignment="leading" spacing={4} frame={{ maxWidth: "infinity", alignment: "leading" }}>
        <Text font="body" lineLimit={1}>{entry.text}</Text>
        {subtitle !== "" && <Text font="subheadline" foregroundColor="secondary" lineLimit={1}>{subtitle}</Text>}
        {preview(entry.note) !== "" && (
          <Text font="caption" foregroundColor="secondary" lineLimit={2}>{preview(entry.note)}</Text>
        )}
      </VStack>
    </HStack>
  )
}

function LexiconScreen() {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([])
  const [entries, setEntries] = useState<LexiconEntry[]>([])
  const [total, setTotal] = useState(0)
  const [query, setQuery] = useState("")
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [editor, setEditor] = useState<LexiconEntry | null>(null)
  const [diff, setDiff] = useState<PhraseDiff | null>(null)
  const [diffWorkspace, setDiffWorkspace] = useState<Workspace | null>(null)
  const [previewing, setPreviewing] = useState(false)

  const reload = () => {
    Promise.all([
      listWorkspaces(),
      listLexiconEntries(query),
      countLexiconEntries(),
    ]).then(async ([rows, nextEntries, nextTotal]) => {
      const refreshed: Workspace[] = []
      for (const row of rows) {
        const value = await refreshWorkspace(row)
        await upsertWorkspace(value)
        refreshed.push(value)
      }
      setWorkspaces(refreshed)
      setEntries(nextEntries)
      setTotal(nextTotal)
      setError(null)
    }).catch(e => setError(String(e))).finally(() => setLoading(false))
  }

  useEffect(() => { reload() }, [query])

  const connect = async () => {
    setError(null)
    try {
      await chooseAndConnectWorkspace()
      reload()
    } catch (e) {
      setError(String(e))
    }
  }

  const previewWorkspace = async (workspace: Workspace) => {
    if (previewing) return
    setPreviewing(true)
    setError(null)
    try {
      const allEntries = await listLexiconEntries("")
      const next = await previewCustomPhraseDiff(workspace, allEntries)
      if (next.inserts.length + next.updates.length + next.invalid.length === 0 && next.same.length === 0) {
        await Dialog.alert({
          title: "没有可对比的内部词条",
          message: "只有填写了编码的内部词条才会进入 custom_phrase.txt 差异。请先给词条补上编码。",
        })
        return
      }
      setDiff(next)
      setDiffWorkspace(workspace)
    } catch (e) {
      await Dialog.alert({ title: "无法预览差异", message: String(e) })
    } finally {
      setPreviewing(false)
    }
  }

  const overlay = error != null
    ? <ContentUnavailableView title="无法读取词库" systemImage="exclamationmark.triangle" description={error} />
    : undefined

  return (
    <NavigationStack>
      <List
        navigationTitle="词库中心"
        navigationBarTitleDisplayMode="large"
        listStyle="insetGrouped"
        overlay={overlay}
        toolbar={editor != null || diff != null ? undefined : {
          primaryAction: <Button title="新建" systemImage="plus" action={() => setEditor(emptyEntry())} />,
          topBarTrailing: <Button title="连接目录" systemImage="folder.badge.plus" action={connect} />,
        }}
        sheet={
          editor != null
            ? {
                isPresented: true,
                onChanged: presented => { if (!presented) setEditor(null) },
                content: (
                  <LexiconEditor
                    key={editor.id}
                    entry={editor}
                    onClose={saved => {
                      setEditor(null)
                      if (saved) reload()
                    }}
                  />
                ),
              }
            : diff != null
              ? {
                  isPresented: true,
                  onChanged: presented => {
                    if (!presented) {
                      setDiff(null)
                      setDiffWorkspace(null)
                    }
                  },
                  content: (
                    <PhraseDiffSheet
                      diff={diff}
                      onClose={() => {
                        setDiff(null)
                        setDiffWorkspace(null)
                      }}
                      onCommit={async () => {
                        if (diffWorkspace == null) throw new Error("没有可提交的工作区")
                        const allEntries = await listLexiconEntries("")
                        const result = await commitCustomPhraseDiff(diffWorkspace, allEntries, diff.hash)
                        await Dialog.alert({
                          title: "已提交",
                          message: `新增 ${result.inserted} 条，更新 ${result.updated} 条。备份目录：ToolboxBackups`,
                        })
                        setDiff(null)
                        setDiffWorkspace(null)
                      }}
                      onImportExternal={async () => {
                        if (diffWorkspace == null) throw new Error("没有可导入的工作区")
                        const result = await importExternalPhrases(
                          diff.externalOnly.map(item => ({
                            text: item.text,
                            code: item.code,
                            weight: item.externalWeight,
                            workspaceId: diffWorkspace.id,
                          })),
                        )
                        await Dialog.alert({
                          title: "已导入内部词库",
                          message: `导入 ${result.imported} 条，跳过 ${result.skipped} 条已存在词条。没有改 custom_phrase.txt。`,
                        })
                        const allEntries = await listLexiconEntries("")
                        const next = await previewCustomPhraseDiff(diffWorkspace, allEntries)
                        setDiff(next)
                        reload()
                      }}
                    />
                  ),
                }
              : undefined
        }
      >
        {workspaces.length > 0 && (
          <Section header={<Text>工作区</Text>} footer={<Text>点万象目录预览差异。提交写回万象，导入只进内部词库。</Text>}>
            {workspaces.map(workspace => (
              <WorkspaceRow
                key={workspace.id}
                workspace={workspace}
                reload={reload}
                onPreview={() => previewWorkspace(workspace)}
              />
            ))}
          </Section>
        )}
        <Section>
          <TextField
            title="搜索"
            value={query}
            onChanged={setQuery}
            prompt="词语、编码或备注"
          />
        </Section>
        <Section
          header={<Text>内部词库</Text>}
          footer={<Text>{loading ? "正在读取…" : `共 ${total} 条。点按复制，左滑编辑，右滑删除。`}</Text>}
        >
          {entries.length === 0 ? (
            <VStack alignment="leading" spacing={6} padding={{ top: 4, bottom: 8 }}>
              <Text>{query ? "没有匹配的词条" : "还没有内部词条"}</Text>
              <Text font="caption" foregroundColor="secondary">
                右上角新建，或从万象差异里导入仅外部存在的词条。
              </Text>
            </VStack>
          ) : entries.map(entry => (
              <LexiconRow
                key={entry.id}
                entry={entry}
                onEdit={() => setEditor(entry)}
                reload={reload}
              />
            ))}
        </Section>
      </List>
    </NavigationStack>
  )
}
// ---- features/settings/SettingsScreen.tsx ----
function SettingsScreen() {
  const [settings, setSettings] = useState<AppSettings>(() => loadSettings())

  const update = (patch: Partial<AppSettings>) => {
    const next = { ...settings, ...patch }
    setSettings(next)
    saveSettings(next)
  }

  return (
    <NavigationStack>
      <Form
        navigationTitle="设置"
        navigationBarTitleDisplayMode="large"
        formStyle="grouped"
      >
        <Section header={<Text>剪贴板</Text>} footer={<Text>脚本在前台时监听；回到前台会补采。点列表即可复制。</Text>}>
          <Toggle title="采集文本和链接" value={settings.captureText} onChanged={value => update({ captureText: value })} />
          <Picker
            title="重复内容"
            value={settings.duplicatePolicy}
            onChanged={value => update({ duplicatePolicy: value as DuplicatePolicy })}
          >
            <Text tag="ignore">忽略</Text>
            <Text tag="moveToTop">更新到顶部</Text>
            <Text tag="keepCopy">保留副本</Text>
          </Picker>
          <Stepper
            title={`最多保留 ${settings.maxItems} 条`}
            onIncrement={() => update({ maxItems: Math.min(2000, settings.maxItems + 100) })}
            onDecrement={() => update({ maxItems: Math.max(100, settings.maxItems - 100) })}
          />
          <Stepper
            title={settings.retentionDays === 0 ? "永久保留非收藏" : `保留 ${settings.retentionDays} 天`}
            onIncrement={() => update({ retentionDays: Math.min(365, settings.retentionDays + 5) })}
            onDecrement={() => update({ retentionDays: Math.max(0, settings.retentionDays - 5) })}
          />
        </Section>

        <Section header={<Text>词库</Text>} footer={<Text>连接目录、预览差异和提交都在「词库」页完成。不会修改 userdb、gram 或官方 dicts。</Text>}>
          <HStack>
            <Text>写入方式</Text>
            <Spacer />
            <Text foregroundColor="secondary">预览后确认</Text>
          </HStack>
        </Section>

        <Section header={<Text>关于</Text>}>
          <HStack>
            <Text>版本</Text>
            <Spacer />
            <Text foregroundColor="secondary">0.2.3</Text>
          </HStack>
          <HStack>
            <Text>数据</Text>
            <Spacer />
            <Text foregroundColor="secondary">本机 SQLite</Text>
          </HStack>
        </Section>
      </Form>
    </NavigationStack>
  )
}
// ---- app/App.tsx ----
type TabID = "clipboard" | "snippets" | "text" | "lexicon" | "settings"

function App() {
  const selection = useObservable<TabID>("clipboard")

  return (
    <TabView selection={selection}>
      <Tab title="剪贴板" systemImage="clipboard.fill" value="clipboard">
        <ClipboardScreen />
      </Tab>
      <Tab title="常用语" systemImage="text.bubble.fill" value="snippets">
        <SnippetsScreen />
      </Tab>
      <Tab title="文本" systemImage="text.alignleft" value="text">
        <TextLabScreen />
      </Tab>
      <Tab title="词库" systemImage="books.vertical.fill" value="lexicon">
        <LexiconScreen />
      </Tab>
      <Tab title="设置" systemImage="gearshape.fill" value="settings">
        <SettingsScreen />
      </Tab>
    </TabView>
  )
}
// ---- index.tsx ----
async function presentFatalError(error: unknown) {
  await Navigation.present({
    element: (
      <ContentUnavailableView
        title="工具箱无法启动"
        systemImage="exclamationmark.triangle.fill"
        description={String(error)}
      />
    ),
  })
}

async function run() {
  let removeResumeListener: (() => void) | null = null
  try {
    await migrateDatabase()
    await captureIfChanged(loadSettings())

    removeResumeListener = Script.onResume(() => {
      captureIfChanged(loadSettings()).catch((error: unknown) => {
        console.error("Resume capture failed", error)
      })
    })

    await Navigation.present({
      element: <App />,
    })
  } catch (error) {
    console.error("NativeToolbox startup failed", error)
    await presentFatalError(error)
  } finally {
    removeResumeListener?.()
    Script.exit()
  }
}

run()
